In [ ]:
import pandas as pd 
import os 

RAW_DATA_DIR = "../data/raw"

tickers = ["AAPL", "MSFT", "GOOGL", "AMZN"]

dfs = []
for ticker in tickers:
    file_path = os.path.join(RAW_DATA_DIR,ticker +"_1d.csv")
    df = pd.read_csv(file_path)
    display(df.head())
    df['Date'] = pd.to_datetime(df['Date'])
    df = df.set_index('Date')
    display(df.head())
    dfs.append(df)

               Close      High       Low      Open     Volume
Date
1990-01-02  0.260949  0.262700  0.245187  0.246939  183198400
1990-01-03  0.262700  0.266204  0.262700  0.266204  207995200
1990-01-04  0.263577  0.271457  0.260949  0.267955  221513600
1990-01-05  0.264452  0.267955  0.259198  0.264452  123312000
1990-01-08  0.266204  0.266204  0.259198  0.262700  101572800

               Close      High       Low      Open     Volume
Date
1990-01-02  0.376482  0.376482  0.365347  0.370119   53035200
1990-01-03  0.378604  0.382845  0.375422  0.379664  113774400
1990-01-04  0.389739  0.390269  0.376482  0.378604  125740800
1990-01-05  0.380194  0.390269  0.379664  0.388148   69566400
1990-01-08  0.386027  0.386027  0.375422  0.379664   58982400

               Close      High       Low      Open     Volume
Date
2004-08-19  2.492181  2.584576  2.383393  2.483736  893181924
2004-08-20  2.690134  2.709259  2.496155  2.508822  456686856
2004-08-23  2.717207  2.818544  2.708514  2.750738  365122512
2004-08-24  2.604694  2.771850  2.572406  2.762908  304946748
2004-08-25  2.632761  2.682435  2.580105  2.606930  183772044

               Close      High       Low      Open      Volume
Date
1997-05-15  0.097917  0.125000  0.096354  0.121875  1443120000
1997-05-16  0.086458  0.098958  0.085417  0.098438   294000000
1997-05-19  0.085417  0.088542  0.081250  0.088021   122136000
1997-05-20  0.081771  0.087500  0.081771  0.086458   109344000
1997-05-21  0.071354  0.082292  0.068750  0.081771   377064000

In [1]:
from ipywidgets import interact

import matplotlib.pyplot as plt
def show_raw_data(i):
    df = dfs[i]
    ticker = tickers[i]
    plt.figure(figsize=(14, 6))
    plt.plot(df['Close'], label="Close Price", linewidth=1.2)
    plt.title(f"{tickers[i]} Close Price Over Time", fontsize=16)
    plt.xlabel("Date")
    plt.ylabel("Price")
    plt.grid(True, alpha=0.3)
    plt.legend()
    plt.show()


interact(show_raw_data, i=(0, len(tickers)-1))

NameError: name 'tickers' is not defined